version: 0.4.1.{build}
skip_tags: true
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(APPVEYOR_REPO_COMMIT)'
before_build:
 - nuget restore -DisableParallelProcessing
build:
  project: Mondo.sln
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
test:
  assemblies: Mondo.Tests\bin\Release\Mondo.Tests.dll
nuget:
  project_feed: true
  disable_publish_on_pr: true
