version: 0.1.0.{build}
environment:
  nuget_version: 0.1.0.0-beta
skip_tags: true
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: Mondo\Properties\AssemblyInfo.cs
  assembly_version: '$(nuget_version)'
  assembly_file_version: '$(nuget_version)'
  assembly_informational_version: '$(APPVEYOR_REPO_COMMIT)'
before_build:
 - nuget restore
build:
  project: Mondo.sln
  verbosity: minimal
after_build:
- cmd: nuget pack Mondo.nuspec -version "%nuget_version%"
- cmd: nuget pack Mondo.symbols.nuspec -version "%nuget_version%" -Symbols
test:
  assemblies: Mondo.Tests\bin\Release\Mondo.Tests.dll
artifacts:
- path: '*.nupkg'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
