version: 0.4.0.{build}
skip_tags: true
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(APPVEYOR_REPO_COMMIT)'
before_build:
 - nuget restore -DisableParallelProcessing
build:
  project: Mondo.sln
  verbosity: minimal
test:
  assemblies: Mondo.Tests\bin\Release\Mondo.Tests.dll
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: qHy33ydNn+MvJHP52iESnMF++FFMNgtQmeBAc1gfwQQUkosyHp6n2qWWI6IUHbTs
  on:
    branch: master
    appveyor_repo_tag: true